# Generated by Django 4.1.4 on 2023-03-24 20:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project', models.CharField(max_length=50, verbose_name='Название проекта')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('edition_key', models.PositiveSmallIntegerField(default=1000)),
                ('project_type', models.CharField(choices=[('external', 'Внешний проект'), ('service', 'Сервисный проект'), ('research', 'Исследовательский проект')], max_length=100, verbose_name='Тип проекта')),
                ('target_groups', models.CharField(max_length=100, verbose_name='Целевые группы')),
                ('manager_email', models.EmailField(max_length=254, verbose_name='Email руководителя')),
                ('implementation_period', models.CharField(choices=[('One', 'На один семестр'), ('Two', 'На два семестра'), ('Tree', 'На три семестра'), ('More', 'На большее количество семестров')], max_length=50, verbose_name='Срок реализации')),
                ('project_status', models.CharField(choices=[('opened', 'Набор открыт'), ('closed', 'Набор закрыт'), ('under_review', 'Проект на рассмотрении'), ('rejected', 'Проект отклонён')], default='under_review', max_length=15, verbose_name='Статус проекта')),
                ('short_project_description', models.CharField(max_length=150, verbose_name='Краткое описание проекта')),
                ('long_project_description', models.TextField(verbose_name='Полное описание проекта')),
                ('poster', models.ImageField(upload_to='uploads/img/%Y/%m/%d/', verbose_name='Постер')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Email')),
                ('secondname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=50, verbose_name='Имя')),
                ('group', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Некорректное название группы', regex='([а-яА-ЯёЁ]{1,4}\\d?-[1-9а-яА-ЯёЁ]{1,4}\\d?)|Преподаватель')], verbose_name='Группа')),
                ('state', models.CharField(choices=[('Преподаватель', 'Сотрудник ИАТЭ'), ('Куратор', 'Менеджер проекта'), ('Подтверждён', 'Участник в команде'), ('Отклонён', 'Участник не в команде'), ('На рассмотрении', 'Заявка рассматривается'), ('Не подан', 'Заявка не подана')], default='Не подан', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_Free', models.BooleanField(default=True)),
                ('current_project', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project', verbose_name='Проект студента')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=100, verbose_name='Заголовок')),
                ('publishing_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('text', models.TextField(verbose_name='Текст')),
                ('file', models.FileField(blank=True, upload_to='uploads/files/%Y/%m/%d/', verbose_name='Прилагаемый файл')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teammember', verbose_name='Автор')),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'is_Free': True}, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='main.teammember', verbose_name='Руководитель проекта'),
        ),
    ]
